### ISSUE TITLE
questions and a suggestion

### ISSUE THREAD

**Issue by mtk** [thread314/intuitive-tab-line-mode#1]
1) does killing the buffer kill the tab?
2) does "find-file" create a new tab?
3) have you thought about submitting this to MELPA?  you'll get a thorough review (worth the time, IMHO).

**Comment by thread314** [comment]
1. Yes. Optionally you can call `my/drop-tab` to remove the tab without killing the buffer.
2. Yes.
3. I had not thought of this, but an interesting idea. I didn't have the sense that there would be enough demand to warrant this, but it might be worth it if only for the review. Thanks for the suggestion. :)
