### ISSUE TITLE
[Feature request] A command to hide a tab

### ISSUE THREAD

**Issue by morgandavidson** [thread314/intuitive-tab-line-mode#7]
It doesn't exist in web browsers, but I think that the ability to Hide/Show a tab would be quite useful in Emacs. 

Showing a tab is already feasible if you select a hidden buffer from `M-x switch-to-buffer` but there is no possibility of hiding a tab yet.

The use case would be to only show the tabs that you are currently using and hide the others.

**Comment by thread314** [comment]
Tell me if I'm not understanding correctly, but it sounds like this is exactly what `intuitive-tab-line-drop-tab` does?

For that matter, `intuitive-tab-line-manually-add-current-buffer-to-tab` allows you to manually add the current buffer to the tab-line. 

Is this the behaviour you were after?

**Comment by morgandavidson** [comment]
Indeed `intuitive-tab-line-drop-tab` exactly does what I had in mind. I should have read the documentation more carefully. Sorry about that...
